
### 说明

异常处理机制的设计多是为了处理同步异常，例如数组范围检查和 I/O 出错。

异步事件，如键盘中断和明确的算术错误不一定是异常，也不能直接由这种机制处理。许多系统提供了用于处理异步问题的有关机制(如信号)。

异常处理机制是一种非局部的控制结构，基于堆栈回退，也可以看作是另一种返回机制。

C++ 中异常处理机制的设计能够有效用于并发程序，只要程序员(或系统)遵守基本的并发规则。


### C++ 中异常的定义和使用

异常经常被按照一个个库或者按照一个个子系统，定义为一些层次结构。
```c++
    class Matherr {};
    class Overflow : public Matherr {};
    class Underflow : public Matherr {};
    class Zerodivide : public Matherr {};
    // ...
```

为避免抛出的异常可能因为捕捉而被"切割"，常常用指针或引用来避免信息的永久性丢失。
```c++
    void f() {
        try {
            // ...
        }
        catch (Matherr& m) {    // 使用引用或指针
            // ...
        }
    }
```

### 捕获异常

语法结构
```c++
    void f() {
        try {
            throw E();
        }
        catch (H) {
            // 异常处理
        }
    }
```

在 main 函数中捕捉公共的异常：
```c++
    int main() {
        try {
            // ... demo
            
            return 0;
        }
        catch (out_of_range) {
            std::cerr << "range error\n";
        }
        catch (...) {
            std::cerr << "unknown exception thrown\n";
        }
        
        return -1;
    }
```

一般采用用户定义类型作为异常，而不用内部类型:
```c++
    namespace Error {
        struct Syntax_error {
            const char* p;
            Syntax_error(const char* q) { p = q };
        };
    }
    try {
        // ...
        throw Error::Syntax_error("bad error");
    }
    catch (Error::Syntax_error e) {
        std::cerr << "syntax error: " << e.p << std::endl;  // "syntax error: bad error"
    }
```
    
### 动态异常指定 dynamic exception specification

旧式代码中会通过动态异常指定来对特定异常类型进行处理
```c++
    double myfunction(char param) throw(int);
```
表示对于非 int 类型异常，myfunction 会调用 std::unexpected 进行处理；对于 int 类型异常，其会寻找相关异常处理句柄按异常处理。

如果抛出类型为空，则对所有类型异常都调用 std::unexpected 进行处理:
```c++
    int myfunction(int param) throw();  // all exception call unexpected
```

如果进行动态异常指定，对所有类型异常都寻找相关异常句柄处理:
```c++
    int myfunction(int param);          // normal exception handling
```
动态异常指定现在很少用了，估计是现在的代码太复杂了。


### 标准异常

C++ 定义了一个标准异常类 `std::exception`, 用户可以根据其派生出自己的异常类, 并重写 std::exception 的虚函数 what 来描述自己定义的异常。

通过设置 std::exception 引用类型句柄，来实现对 std::exception 及其派生类所定义的异常的捕获。

[示例程序](t/14_exception.cpp)

  
### C++ 标准库中定义的异常有:

|     exception     |                  description                   |
|-------------------|------------------------------------------------|
| bad_alloc         | new 失败时抛出                                 |
| bad_cast          | dynamic_cast 转换失败后抛出                    |
| bad_exception     | 某些动态异常指定抛出                           |
| bad_typeid        | typeid 抛出                                    |
| bad_function_call | 空函数对象抛出                                 |
| bad_weak_ptr      | 向 shared_ptr 传递一个被破坏的 weak_ptr 时抛出 |


### C++ 标准库也自己从 std::exception 派生了两个通用异常类供用户使用:

|     exception     |                  description                   |
|-------------------|------------------------------------------------|
| logic_error       | 程序内在逻辑相关错误                           |
| runtime_error     | 运行时检测到的错误                             |
